### PR TITLE
Revert "Change tags for insensitive, cleanup already existent tags/tagged items"

### PR DESCRIPTION
**Pull request by thibaudcolas**
Reverts springload/madewithwagtail#43 – The migration takes forever during deployment, do not know why exactly.

https://codeship.com/projects/79308/builds/18955821

### CODE REVIEW

**Comment by thibaudcolas** [comment]
@x-warrior the migration within the build took forever so I stopped the build, reverted the change and pushed/deployed again. Now it seems like the migration was successful, even though it didn't complete. Was I too impatient? (I stopped the build after ±25mins, whereas the migration took a few seconds on my machine).

Could you investigate this? I don't want to touch it too much without anyone else around to help out with rollbacks and the likes if necessary.

**Comment by thibaudcolas** [comment]
I got some time to troubleshoot this, I think it stalled because of the migrate command asking for user input. It actually did this too when I ran it locally but I overlooked it:

```
Running migrations:
  Rendering model states... DONE
  Applying core.0005_auto_20161004_1431... OK
The following content types are stale and need to be deleted:

    wagtailsearch | editorspick

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel:
```

**Comment by x-warrior** [comment]
Yes. That is the problem.

**Comment by thibaudcolas** [comment]
For the record: Added the no `--noinput` in the migrate step of the deployment process on @x-warrior's suggestion, so shouldn't happen again.

**Pull request merged**
