### PR TITLE
Fixes madewithwagtail provision

### PR DESCRIPTION
**Pull request by x-warrior**
- Updated wagtail to 1.4.6
   - Wagtail 1.4.4 was requiring htmllib 0.999999 and it was breaking because of it.
   - Wagtail 1.4.6 fix html5lib version http://docs.wagtail.io/en/v1.6.2/releases/1.4.6.html
- django-debug-toolbar updated
- Changed install_req to pip install -r

### CODE REVIEW

**Comment by x-warrior** [comment]
Just noticed an existent issue for this. 

Fixes #34

**Comment by thibaudcolas** [comment]
👍  Looks good to me, although I'm surprised it works without `djangorestframework` in the requirements. Where does it get pulled from?

For bullet point 4 in #34, I think it was just because the provision failed and it didn't load the initial data / fixtures.

**Comment by loicteixeira** [comment]
@thibaudcolas: Django REST Framework is a dependency of Wagtail since [1.1](http://docs.wagtail.io/en/v1.6.3/releases/1.1.html#the-wagtailapi-module-now-uses-django-rest-framework).

**Comment by x-warrior** [comment]
Loic is correct, it comes from Wagtail setup: https://github.com/torchbox/wagtail/blob/3e66a137538057060265fad435bd6878b07f0c5a/setup.py

**Pull request merged**
