### PR TITLE
Remove compiled assets

### LINKED ISSUE #33: Stop committing compiled, unminified static assets
The static assets should be built with the right configuration at deployment time instead of being stored in git.

This makes the repository categorised as CSS instead of Python on GitHub.

### PR DESCRIPTION
**Pull request by loicteixeira**
Fix #33

- [X] Update CI build.
   - The build now runs: `nvm install`, `npm install` and `npm run dist`
   - It was already syncing the files via `rsync`.
- [x] Fix `npm install` error.
- [X] Remove compiled assets
- [X] Update .gitignore

### CODE REVIEW

**Comment by loicteixeira** [comment]
The `npm install` error happens both locally and in the CI. While none of the steps actually fail and the assets are still properly generated with `npm run build/dist`, it's probably worth fixing.

```
-/sass/node-sass/releases/download/v3.10.0/linux-x64-46_binding.node
-e/rof/src/github.com/springload/madewithwagtail/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-46/binding.node

> node-sass@3.10.0 postinstall /home/rof/src/github.com/springload/madewithwagtail/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

|e/rof/src/github.com/springload/madewithwagtail/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-46/binding.node" exists. 
testing binary.
-e/rof/src/github.com/springload/madewithwagtail/node_modules/gulp-pleeease/node_modules/pleeease/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/linux-x64-node-4.6/binding.node

> node-sass@2.0.1 postinstall /home/rof/src/github.com/springload/madewithwagtail/node_modules/gulp-pleeease/node_modules/pleeease/node_modules/node-sass
> node scripts/build.js

module.js:327
throw err;
^

Error: Cannot find module '/home/rof/src/github.com/springload/madewithwagtail/node_modules/gulp-pleeease/node_modules/pleeease/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:139:18)
at node.js:990:3
Build failed
gulp-rename@1.2.2 node_modules/gulp-rename
```

**Comment by thibaudcolas** [comment]
@loicteixeira I double checked the install error, it is within `pleeease` from which we don't use the sass compilation. So innocuous.

I took a bit of time to update / clean up the install process anyway, & upgrade to node 6 & npm 3.

**Comment by loicteixeira** [comment]
Thanks @thibaudcolas. I'll try to deploy the changes during the week and monitor to make sure everything go smoothly.

**Comment by loicteixeira** [comment]
Done. Static files are copied over properly during build process.

**Pull request merged**
